"""
 * bin2c.py — embed a binary blob as a C array.
 *
 * The initrd has to reach the kernel somehow before there is a filesystem to
 * read it from, so the build compiles it into a C translation unit. Generated
 * rather than checked in because a 100 KB hex array in version control is a
 * merge conflict waiting to happen.
 *
 * The array is emitted as `unsigned char` rather than `unsigned int`: a 32-bit
 * array would be a quarter the size but a quarter the elements, and the element
 * type has to match what the blob reader casts to. Size over density.
"""

import argparse
import sys

CHUNK = 16


def emit(data: bytes, name: str, out=sys.stdout) -> None:
    out.write(f"/* Generated by tools/bin2c.py. Do not edit. */\n\n")
    out.write(f"const unsigned long {name}_size = {len(data)}UL;\n\n")
    out.write(f"const unsigned char {name}[] = {{\n")

    for i in range(0, len(data), CHUNK):
        chunk = data[i:i + CHUNK]
        out.write("\t" + "".join(f"0x{b:02x}, " for b in chunk).rstrip() + "\n")

    out.write("};\n")


def main() -> int:
    ap = argparse.ArgumentParser(description="embed a binary as a C array")
    ap.add_argument("input")
    ap.add_argument("name")
    args = ap.parse_args()

    with open(args.input, "rb") as fh:
        data = fh.read()

    if not data:
        print(f"error: {args.input} is empty", file=sys.stderr)
        return 1

    emit(data, args.name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
