#!/usr/bin/env python3
"""Convert a kbd-style PSF/PSF2 console font into a C source array.

Usage: psf2c.py <font.psf|font.psf.gz> <out.c> <symbol>

The generated array is `symbol[256][16]`, one byte per row, MSB leftmost —
matching the layout the VGA text-mode font ROM and the PSF format both use.
"""

import gzip
import sys


def load(path: str) -> bytes:
    with open(path, "rb") as fh:
        raw = fh.read()
    if raw[:2] == b"\x1f\x8b":
        raw = gzip.decompress(raw)
    return raw


def parse(raw: bytes) -> tuple[int, bytes, int]:
    magic32 = int.from_bytes(raw[0:4], "little")
    if magic32 == 0x864AB572:  # PSF2
        # version(4) headersize(4) flags(4) length(4) charsize(2) height(2) width(2)
        header_size = int.from_bytes(raw[8:12], "little")
        length = int.from_bytes(raw[16:20], "little")
        charsize = int.from_bytes(raw[20:22], "little")
        return length, raw[header_size : header_size + length * charsize], charsize
    if magic32 & 0xFFFF == 0x00B5:  # PSF1
        charsize = raw[2]
        length = raw[3] | (raw[4] << 8)
        return length, raw[256 : 256 + length * charsize], charsize
    raise SystemExit(f"unsupported PSF magic 0x{magic32:08x}")


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__, file=sys.stderr)
        return 2
    _, font_path, out_path, symbol = sys.argv
    raw = load(font_path)
    length, glyphs, height = parse(raw)
    rows = 16
    # Reject implausible headers up front: a misparsed magic used to turn the
    # resample loop below into a multi-gigabyte allocation.
    if length <= 0 or length > 65536:
        raise SystemExit(f"implausible glyph count {length}")
    if height <= 0 or height > 256:
        raise SystemExit(f"implausible glyph height {height}")
    if len(glyphs) < length * height:
        raise SystemExit(f"truncated font data: {len(glyphs)} < {length * height}")

    if height > rows:
        step = height // rows
        if step < 1:
            raise SystemExit(f"degenerate resample stride for height {height}")
        glyphs = b"".join(glyphs[i * height : (i + 1) * height : step] for i in range(length))
    elif height < rows:
        glyphs = b"".join(
            glyphs[i * height : (i + 1) * height] + b"\x00" * (rows - height) for i in range(length)
        )
    glyphs = glyphs[:256 * rows].ljust(256 * rows, b"\x00")

    with open(out_path, "w") as out:
        out.write("/* Generated by tools/psf2c.py — do not edit by hand. */\n\n")
        out.write(f"#include <stdint.h>\n\n")
        out.write(f"const uint8_t {symbol}[256][16] = {{\n")
        for index in range(256):
            chunk = glyphs[index * rows : (index + 1) * rows]
            body = ", ".join(f"0x{b:02x}" for b in chunk)
            out.write(f"    {{ {body} }}, /* 0x{index:02x} */\n")
        out.write("};\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
